set(prefix "${CMAKE_BINARY_DIR}/deps")
set(PAIRING_LIBRARY "${prefix}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}pairing${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(PAIRING_INCLUDE_DIR "${prefix}/include")
set(LIBRARY_DIR "${prefix}/lib64/")

ExternalProject_Add(pairing
    PREFIX "${prefix}"
    URL file:///home/x/pairing-ariel.tar.gz
    URL_HASH SHA256=b81cf2491c4158b02e88d588bbfb1e75ab3e40c41f4d3e02c9ae79a1a5980d84
    BUILD_BYPRODUCTS "${PAIRING_LIBRARY}"
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DCMAKE_INSTALL_DIR=<INSTALL_DIR>
    -DCMAKE_LIB_TARGET_LOCATION=${LIBRARY_DIR}
)

add_library(Pairing STATIC IMPORTED)
set_property(TARGET Pairing PROPERTY IMPORTED_CONFIGURATIONS Release)
set_property(TARGET Pairing PROPERTY IMPORTED_LOCATION_RELEASE ${PAIRING_LIBRARY})
set_property(TARGET Pairing PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${PAIRING_INCLUDE_DIR})
add_dependencies(Pairing pairing)
