set(prefix "${CMAKE_BINARY_DIR}/deps")
set(PAIRING_LIBRARY "${prefix}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}pairing${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(PAIRING_INCLUDE_DIR "${prefix}/include")
set(LIBRARY_DIR "${prefix}/lib64/")

ExternalProject_Add(pairing
    PREFIX "${prefix}"
    URL file:///home/x/pairing-ariel.tar.gz
		URL_HASH SHA256=92ce810501b10ff46577b1be6065b8412f2e0c463c510a97ca37d51bf0577e03
    BUILD_BYPRODUCTS "${PAIRING_LIBRARY}"
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DCMAKE_INSTALL_DIR=<INSTALL_DIR>
    -DCMAKE_LIB_TARGET_LOCATION=${LIBRARY_DIR}
)

add_library(Pairing STATIC IMPORTED)
set_property(TARGET Pairing PROPERTY IMPORTED_CONFIGURATIONS Release)
set_property(TARGET Pairing PROPERTY IMPORTED_LOCATION_RELEASE ${PAIRING_LIBRARY})
set_property(TARGET Pairing PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${PAIRING_INCLUDE_DIR})
add_dependencies(Pairing pairing)
