set(prefix "${CMAKE_BINARY_DIR}/deps")
set(PAIRING_LIBRARY "${prefix}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}pairing${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(PAIRING_INCLUDE_DIR "${prefix}/include")
set(LIBRARY_DIR "${prefix}/lib64/")

ExternalProject_Add(pairing
    PREFIX "${prefix}"
    URL file:///home/w/pairing-ariel.tar.gz
    URL_HASH SHA256=c88d8f041067f35cab3b4a0bc9bc31008c11a5b4bac74a5a65d4afb7ecf8bd14
    BUILD_BYPRODUCTS "${PAIRING_LIBRARY}"
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DCMAKE_INSTALL_DIR=<INSTALL_DIR>
    -DCMAKE_LIB_TARGET_LOCATION=${LIBRARY_DIR}
)

add_library(Pairing STATIC IMPORTED)
set_property(TARGET Pairing PROPERTY IMPORTED_CONFIGURATIONS Release)
set_property(TARGET Pairing PROPERTY IMPORTED_LOCATION_RELEASE ${PAIRING_LIBRARY})
set_property(TARGET Pairing PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${PAIRING_INCLUDE_DIR})
add_dependencies(Pairing pairing)
